trigger:
- main  # Déclencher le pipeline lorsque la branche "main" est mise à jour

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildAndTestJob
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'  # Version de Python que vous souhaitez utiliser
      addToPath: true

  - script: |
      python -m venv venv
      source venv/bin/activate
      pip install --upgrade pip
      pip install pytest
      pip install pytest-xdist
      pip install pytest-html
      pip install selenium
    displayName: 'Installer les dépendances'

  - script: |
      BROWSER=chrome pytest -n auto
    displayName: 'Exécuter les tests avec pytest et Selenium'

  - script: |
      pytest --html=report.html --self-contained-html
      mv report.html $(Build.ArtifactStagingDirectory)/test_report.html
    displayName: 'Générer et stocker les rapports de test'

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'test-reports'
      targetPath: $(Build.ArtifactStagingDirectory)/test_report.html
    displayName: 'Télécharger les rapports de test'
